### ISSUE TITLE
Иногда бот падает при прокрутке колеса

### ISSUE THREAD

**Issue by Nord1cWarr1or** [meKryztal/agent301#2]
```
Traceback (most recent call last):
File "/home/wp/tgbots/agent301/venv/lib/python3.11/site-packages/requests/models.py", line 974, in json
return complexjson.loads(self.text, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/wp/.pyenv/versions/3.11.5/lib/python3.11/json/__init__.py", line 346, in loads
return _default_decoder.decode(s)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/wp/.pyenv/versions/3.11.5/lib/python3.11/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/wp/.pyenv/versions/3.11.5/lib/python3.11/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/wp/tgbots/agent301/wheel.py", line 118, in <module>
main()
File "/home/wp/tgbots/agent301/wheel.py", line 111, in main
claim_wheel(authorization, username)
File "/home/wp/tgbots/agent301/wheel.py", line 71, in claim_wheel
json_responsew = responsew.json()
^^^^^^^^^^^^^^^^
File "/home/wp/tgbots/agent301/venv/lib/python3.11/site-packages/requests/models.py", line 978, in json
raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Nord1cWarr1or** [comment]
Исправлено в https://github.com/meKryztal/agent301/commit/b260d931150bb9fef35920d55a1d8e864b76cec7
